name: "Fehlerbericht"
description: "Erstelle einen Bericht, um uns zu helfen, uns zu verbessern"
title: "[Issue]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **Beschreibe den Fehler**
        Eine klare und präzise Beschreibung des Fehlers.

  - type: textarea
    id: reproduktion
    attributes:
      label: "Reproduktion"
      description: "Schritte zur Reproduktion des Fehlers"
      value: |
        1. Gehe zu '...'
        2. Klicke auf '...'
        3. Scrolle nach unten zu '...'
        4. Fehler sehen

  - type: textarea
    id: erwartetes-verhalten
    attributes:
      label: "Erwartetes Verhalten"
      description: "Eine klare und präzise Beschreibung dessen, was du erwartet hast."
  
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "Falls zutreffend, füge Screenshots hinzu, um das Problem zu erläutern."
  
  - type: input
    id: betriebssystem
    attributes:
      label: "Betriebssystem"
      description: "z.B. Windows, Mac, Linux"
  
  - type: input
    id: browser
    attributes:
      label: "Browser"
      description: "z.B. Chrome, Safari"
  
  - type: input
    id: version
    attributes:
      label: "Version"
      description: "z.B. 22"

  - type: textarea
    id: zusaetzlicher-kontext
    attributes:
      label: "Zusätzlicher Kontext"
      description: "Füge hier zusätzlichen Kontext zum Problem hinzu."
