name: "Funktionsanforderung"
description: "Schlage eine Idee für dieses Projekt vor"
title: "[Feature Request]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        **Ist deine Funktionsanforderung mit einem Problem verbunden? Bitte beschreibe.**
        Eine klare und präzise Beschreibung des Problems. z.B. Ich bin immer frustriert, wenn [...]

  - type: textarea
    id: loesung
    attributes:
      label: "Beschreibe die gewünschte Lösung"
      description: "Eine klare und präzise Beschreibung dessen, was du möchtest."

  - type: textarea
    id: alternativen
    attributes:
      label: "Beschreibe Alternativen, die du in Betracht gezogen hast"
      description: "Eine klare und präzise Beschreibung möglicher Alternativlösungen oder Funktionen, die du in Betracht gezogen hast."

  - type: textarea
    id: zusaetzlicher-kontext
    attributes:
      label: "Zusätzlicher Kontext"
      description: "Füge hier weiteren Kontext oder Screenshots zur Funktionsanforderung hinzu."
